const TYPE = {
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  NUMBER: "NUMBER",
  TEXT: "TEXT",
  MIXED: "MIXED",
};

const OPTIONS = {
  ANSWER_LABELS: "ANSWER_LABELS",
  ANSWER_LABELS_SUFFIX: "ANSWER_LABELS_SUFFIX",
  MULTIPLE_ANSWERS: "MULTIPLE_ANSWERS",
  CASE_SENSITIVE: "CASE_SENSITIVE",
};

const DEFAULT_OPTIONS = {
  [OPTIONS.ANSWER_LABELS]: true,
  [OPTIONS.ANSWER_LABELS_SUFFIX]: ") ",
  [OPTIONS.MULTIPLE_ANSWERS]: false,
  [OPTIONS.CASE_SENSITIVE]: false,
};

const STATUS = {
  IDLE: "IDLE",
  ONGOING: "ONGOING",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED"
};

export { TYPE, OPTIONS, DEFAULT_OPTIONS, STATUS };
